// ╔══════════════════════════════════════════════════════════════════╗
// ║  PADMAGNET PROJECT BACKLOG                                      ║
// ║                                                                 ║
// ║  Single source of truth for project tasks.                      ║
// ║  Claude updates this file after each session.                   ║
// ║  Status: done | in-progress | pending | blocked | deferred      ║
// ╚══════════════════════════════════════════════════════════════════╝

export const BACKLOG = [
  {
    category: "Completed — Foundation & Core",
    items: [
      { id: "T01", title: "Run migrations 009-020 (landlord workflow, billing, storage, etc.)", status: "done", date: "2026-03-03" },
      { id: "PM-09", title: "Google Geocoding key configured", status: "done", date: "2026-03-03" },
      { id: "PM-10", title: "Photo upload to Supabase Storage", status: "done", date: "2026-03-03" },
      { id: "PM-11", title: "PadScore lease_too_short check (server + client)", status: "done", date: "2026-03-03" },
      { id: "PM-12", title: "Stripe API routes (checkout, webhook, renew) — code written, not wired", status: "done", date: "2026-03-03" },
      { id: "PM-13", title: "Cron jobs: listing expiration + expiry emails", status: "done", date: "2026-03-03" },
      { id: "PM-14", title: "Mobile owner create flow (8-step wizard)", status: "done", date: "2026-03-03" },
      { id: "PM-15", title: "Mobile listing preview + relist screens", status: "done", date: "2026-03-03" },
      { id: "PM-16", title: "Auth flow workarounds for Expo Go (magic link, deep links)", status: "done", date: "2026-03-03" },
      { id: "PM-17", title: "SMTP fix (Resend key rotation in Supabase Auth)", status: "done", date: "2026-03-03" },
      { id: "PM-18", title: "Design system unification (AuthHeader, app-theme.css, COLORS)", status: "done", date: "2026-03-02" },
    ],
  },
  {
    category: "Completed — Recent Sessions",
    items: [
      { id: "PM-01", title: "Product display flow — API, hook, ProductCard, Services screen", status: "done", date: "2026-03-04" },
      { id: "PM-02", title: "Fix product data freshness (Next.js fetch cache + no-store)", status: "done", date: "2026-03-04" },
      { id: "PM-03", title: "Supabase Realtime on products table", status: "done", date: "2026-03-04" },
      { id: "PM-04", title: "Products admin panel — audience split, hard delete, inline edit", status: "done", date: "2026-03-03" },
      { id: "PM-05", title: "Admin dashboard — standardize Listings + Audit panels to AdminTable", status: "done", date: "2026-03-03" },
      { id: "PM-06", title: "Owner tab reorder (Listings > Services > Messages > Profile)", status: "done", date: "2026-03-04" },
      { id: "PM-07", title: "Dashboard: Wired to App column, Last Modified column, updated_at trigger", status: "done", date: "2026-03-04" },
      { id: "PM-08", title: "Mobile \\n line break rendering in ProductCard", status: "done", date: "2026-03-04" },
      { id: "PM-19", title: "Backlog dashboard panel (data file + UI + animated sidebar button)", status: "done", date: "2026-03-04" },
      { id: "PM-20", title: "Fix profiles.role default from admin to tenant", status: "done", date: "2026-03-04" },
      { id: "PM-21", title: "Fix test user roles (info@ → tenant, maintenance@ → owner)", status: "done", date: "2026-03-04" },
      { id: "PM-22", title: "Admin login: forgot password flow (implicit auth, Resend email)", status: "done", date: "2026-03-04" },
      { id: "PM-23", title: "Admin password reset via Management API", status: "done", date: "2026-03-04" },
      { id: "PM-24", title: "Role-gated admin middleware (profiles.role check)", status: "done", date: "2026-03-04" },
      { id: "PM-25", title: "Fix PKCE recovery flow (server-side code exchange + implicit fallback)", status: "done", date: "2026-03-04" },
      { id: "PM-26", title: "Waitlist role label landlord → owner (DB + landing page)", status: "done", date: "2026-03-04" },
      { id: "PM-27", title: "Delete orphaned chris@floridapm.net (auth + waitlist)", status: "done", date: "2026-03-04" },
      { id: "PM-28", title: "Replace geocode API with local service-area autocomplete in ZonePicker", status: "done", date: "2026-03-05", notes: "Static city/zip data for 5 counties, local filtering, no API calls" },
      { id: "PM-29", title: "Require at least 1 zone in onboarding step 2", status: "done", date: "2026-03-05" },
      { id: "PM-30", title: "Onboarding overhaul: back pill, bigger logo, new copy, remove skip", status: "done", date: "2026-03-05" },
      { id: "PM-31", title: "Onboarding step resumption (persists to AsyncStorage)", status: "done", date: "2026-03-05" },
      { id: "PM-32", title: "Fix VirtualizedList nesting error in ZonePicker", status: "done", date: "2026-03-05" },
      { id: "PM-33", title: "Fix keyboard covering zone search on onboarding step 2", status: "done", date: "2026-03-05" },
      { id: "PM-34", title: "Property type onboarding step (7 types, chip selectors, PadScore integration)", status: "done", date: "2026-03-05" },
      { id: "PM-35", title: "Text-based logo on welcome screen (white Pad + orange Magnet)", status: "done", date: "2026-03-05" },
      { id: "PM-36", title: "Back pill moved to upper-left + Back text link restored on all steps", status: "done", date: "2026-03-05" },
      { id: "PM-37", title: "Profile button renamed to PadScore™ Preferences", status: "done", date: "2026-03-05" },
      { id: "PM-38", title: "Property types list synced across onboarding, preferences, owner create", status: "done", date: "2026-03-05" },
      { id: "PM-39", title: "Remove Min Budget, Min Lease, Max HOA from tenant preferences UI", status: "done", date: "2026-03-05", notes: "DB columns kept, just hidden from UI" },
      { id: "PM-40", title: "Add association_preferred column + Association chip selector in preferences", status: "done", date: "2026-03-05", notes: "NULL=no pref, true=prefer, false=avoid; 50pt PadScore penalty on mismatch" },
      { id: "PM-41", title: "Replace hoa_mismatch with association_mismatch in PadScore (server+client+admin)", status: "done", date: "2026-03-05", notes: "Uses hoa_fee > 0 as proxy for association until AssociationYN from Bridge" },
      { id: "PM-42", title: "Update preferences footer text + location label", status: "done", date: "2026-03-05" },
      { id: "PM-43", title: "Fix Profile tab crash (move GestureHandlerRootView to root layout)", status: "done", date: "2026-03-05", notes: "Native crash caused by gesture handler scoped to swipe tab only" },
      { id: "PM-44", title: "Swipe undo system (DELETE API + 5s undo button + haptics)", status: "done", date: "2026-03-05", notes: "Single swipe delete + bulk reset endpoints, undo button auto-dismisses" },
      { id: "PM-45", title: "Saved/Passed toggle on Saved tab with remove + reconsider actions", status: "done", date: "2026-03-05", notes: "Pill-style toggle, remove from Saved, reconsider from Passed — both return listing to deck" },
      { id: "PM-46", title: "Reset Swipe History option on Profile screen", status: "done", date: "2026-03-05", notes: "Danger-styled menu item with confirmation, bulk deletes all swipes" },
      { id: "PM-47", title: "Fix swipes not saving — disable Next.js fetch cache on Supabase client", status: "done", date: "2026-03-06", notes: "Next.js 14 cached PostgREST responses by default; stale seed data caused FK violations on swipe POST" },
      { id: "PM-48", title: "Surface swipe errors via Alert instead of silent console.warn", status: "done", date: "2026-03-06", notes: "Also fixed apiFetch header merge order to prevent auth header clobbering" },
      { id: "PM-49", title: "Delete test seed file + improve empty state messaging", status: "done", date: "2026-03-06", notes: "Removed seed_test_listings.sql; updated empty states to 'We don't have homes that fit your search yet'" },
      { id: "PM-50", title: "PadScore badge: percentage display, white text, blue bubble", status: "done", date: "2026-03-06" },
      { id: "PM-51", title: "Swipe header: Pad (white) + Magnet (orange) branded logo", status: "done", date: "2026-03-06" },
      { id: "PM-52", title: "Explicit Stack.Screen declarations for all routes in root layout", status: "done", date: "2026-03-06", notes: "Prevents Expo Router auto-discovery issues with owner/, listing/, etc." },
      { id: "PM-53", title: "Unified alerts: migrate all tenant screens from native Alert to custom useAlert", status: "done", date: "2026-03-06", notes: "saved.js, profile.js, useSwipe.js now match owner screen styling" },
      { id: "PM-54", title: "Swipe action buttons: trash icon for skip, 'More Info' label for detail", status: "done", date: "2026-03-06" },
      { id: "PM-55", title: "Saved screen overhaul: Loved/Trash tabs with heart/trash icons + border outline active indicator", status: "done", date: "2026-03-06", notes: "Frosted glass trash button on cards, FontAwesome icons on tabs" },
      { id: "PM-56", title: "Await recordSwipe in handleSwipe to prevent silent save failures", status: "done", date: "2026-03-06", notes: "Card restored to deck on API failure instead of vanishing" },
      { id: "PM-57", title: "Saved page re-fetches on tab focus via useFocusEffect", status: "done", date: "2026-03-06" },
      { id: "PM-58", title: "Reset deck button on swipe screen header", status: "done", date: "2026-03-06", notes: "Confirmation alert, clears all swipes, reloads deck" },
      { id: "PM-59", title: "Swipe reset direction: removed listings return to bottom of deck", status: "done", date: "2026-03-06", notes: "PATCH/POST with direction='reset', listings API sorts _reseen to bottom" },
      { id: "PM-60", title: "Fix Bridge sync missing photos: drop $select to get Media navigation property", status: "done", date: "2026-03-06", notes: "OData $select suppresses navigation properties even with $expand; fetching all fields resolves it" },
      { id: "PM-61", title: "Beach/palm tree placeholder for listings without photos", status: "done", date: "2026-03-06", notes: "SwipeCard, ListingCard, PhotoGallery — deep ocean blue bg, faded emoji, white 'Listing Photo Coming Soon' overlay" },
      { id: "PM-62", title: "Fix deck not refreshing on reset button press", status: "done", date: "2026-03-06", notes: "refresh() didn't clear listings array — deck looked unchanged. Now clears to show loading spinner before re-fetch" },
      { id: "PM-63", title: "Display field config system — DB table, admin panel, config-driven ListingInfo", status: "done", date: "2026-03-06", notes: "Migration 022: display_field_configs (26 rows) + 5 owner columns. Admin CRUD panel. ListingInfo.js refactored to render from config. Bridge sync now captures PublicRemarks, pool, parking, virtual_tour_url." },
      { id: "PM-64", title: "Remove Treasure Coast city filter, expand to 5-county coverage", status: "done", date: "2026-03-07", notes: "Bridge sync now filters by county (St Lucie, Martin, Palm Beach, Broward, Miami-Dade) with 30-day freshness window. ~11,400 listings." },
      { id: "PM-65", title: "Wire Overview panel to live Supabase data", status: "done", date: "2026-03-07", notes: "4 stat cards, feed health, sync logs, owner listing signup — all live. Demo data removed from OverviewPanel." },
      { id: "PM-66", title: "Admin header: user name bubble + remove county badge", status: "done", date: "2026-03-07" },
      { id: "PM-67", title: "site_config table + /api/admin/config for persistent admin fields", status: "done", date: "2026-03-07", notes: "Bridge portal URL and IDX notes persist across sessions" },
      { id: "PM-68", title: "Bridge sync: per-county fetch + stream-upsert + updated_at deactivation", status: "done", date: "2026-03-07", notes: "Handles 15K+ listings, stays under Bridge 10K $skip limit, Vercel Pro 300s timeout" },
      { id: "PM-69", title: "Mobile: auto-refresh listings on app foreground (AppState listener)", status: "done", date: "2026-03-07", notes: "useListings.js re-fetches on AppState 'active', preserves saved cards" },
      { id: "PM-70", title: "Email footer updated to PadMagnet.com tagline", status: "done", date: "2026-03-07" },
      { id: "PM-71", title: "Photo gallery progress bar (replace dot indicators)", status: "done", date: "2026-03-07", notes: "6px bar at bottom of photo gallery, scales with photo count" },
      { id: "PM-72", title: "Fix duplicate key error on listing loadMore", status: "done", date: "2026-03-07", notes: "Set-based dedup in useListings append" },
      { id: "PM-73", title: "Swipe refresh button: move left of logo, feed-only refresh (no swipe deletion)", status: "done", date: "2026-03-07" },
      { id: "PM-74", title: "Saved screen: trash icon moves card to Trash tab, reconsider uses DELETE", status: "done", date: "2026-03-07", notes: "Fixed swipes_direction_check constraint violation" },
      { id: "PM-75", title: "Restore All button on Trash tab (direction=left only, preserves Loved)", status: "done", date: "2026-03-07", notes: "API updated to accept ?direction= param for selective reset" },
      { id: "PM-76", title: "Remove undo swipe button from swipe screen", status: "done", date: "2026-03-07" },
      { id: "PM-77", title: "Tinder-style swipe gestures on card stack", status: "done", date: "2026-03-07", notes: "Root cause: overflow:hidden on gesture target blocked Android touches. Fix: separate gesture target (no overflow) from visual card. Added velocity-based swipe detection." },
      { id: "PM-78", title: "Swipe overlay icons: heart (save) + trash (skip) in circles, mid-photo placement", status: "done", date: "2026-03-07" },
      { id: "PM-79", title: "Back card offset (9px left, 15px down) for visual deck cue", status: "done", date: "2026-03-07" },
      { id: "PM-80", title: "Empty state icon color set to white, Trash/Loved empty text updated", status: "done", date: "2026-03-07" },
      { id: "PM-81", title: "Fix CardStack render-phase state update (prefetch moved to useEffect)", status: "done", date: "2026-03-07" },
      { id: "PM-82", title: "Rename Reconsider button to Un-Trash", status: "done", date: "2026-03-07" },
      { id: "PM-83", title: "Swipe card wiggle hint on initial app load", status: "done", date: "2026-03-07", notes: "Subtle 8px horizontal shake, fires once via useRef flag" },
      { id: "PM-84", title: "Personalized intro text above card deck with user's first name + PadScore branding", status: "done", date: "2026-03-07" },
      { id: "PM-85", title: "Compact swipe card: remove MLS office, merge city into address, 70/30 photo/info split", status: "done", date: "2026-03-07" },
      { id: "PM-86", title: "Card height reduced to 58% screen for responsive layout on all devices", status: "done", date: "2026-03-07" },
      { id: "PM-87", title: "Fix FontAwesome tab bar icons (font preloading via useFonts splash gate)", status: "done", date: "2026-03-07", notes: "Icons rendered as Unicode before font loaded — added ...FontAwesome.font to useFonts() in root layout" },
      { id: "PM-88", title: "More Info button → standard info icon with white border styling", status: "done", date: "2026-03-07" },
      { id: "PM-89", title: "Shareable listing links: share button + public web page + OG tags + store badges", status: "done", date: "2026-03-07", notes: "Share.share() on mobile, public page at /listing/[id] with OG meta, app store download badges" },
      { id: "PM-90", title: "Share button design: icon+label pill (40x80, accent border, rounded)", status: "done", date: "2026-03-07" },
      { id: "PM-91", title: "Saved screen tab styling: bright white active text, dimmed slate inactive", status: "done", date: "2026-03-07" },
      { id: "PM-92", title: "EAS development build setup (replaces Expo Go for native module support)", status: "done", date: "2026-03-08", notes: "EAS project @cmlundstrom/padmagnet, dev profile builds APK with native modules (Google Maps, expo-navigation-bar)" },
      { id: "PM-93", title: "Google Maps working on Android via EAS dev build", status: "done", date: "2026-03-08", notes: "Root cause: Expo Go can't inject Maps API key into native binary. Fix: EAS dev build + react-native-maps plugin + PROVIDER_GOOGLE. Also fixed HTTP referer restriction on API key." },
      { id: "PM-94", title: "Fix settings route warning (add settings/_layout.js)", status: "done", date: "2026-03-08" },
      { id: "PM-95", title: "Fix tab bar hidden behind Android system nav bar (edge-to-edge mode)", status: "done", date: "2026-03-08", notes: "SafeAreaView edges={['bottom']} on tab layouts. expo-navigation-bar for system nav color match (pending next build)." },
      { id: "PM-96", title: "Draggable column reordering on AdminTable + per-role field visibility", status: "done", date: "2026-03-08", notes: "@dnd-kit on header cells, localStorage persistence, visible_owner column on display_field_configs" },
      { id: "PM-97", title: "Tab bar spacing: marginBottom -21 + expo-navigation-bar color match", status: "done", date: "2026-03-08", notes: "Recovers ~20px of screen real estate on Android" },
      { id: "PM-98", title: "Google Maps API key rotated to EAS Secret", status: "done", date: "2026-03-08", notes: "Old key deleted, new key in EAS Secret + local envs only, no hardcoded values in repo" },
      { id: "PM-99", title: "PadScore association fix: one-directional penalty only", status: "done", date: "2026-03-08", notes: "Only penalize when tenant says No + property has HOA. Yes and No Preference = zero impact." },
      { id: "PM-100", title: "Onboarding: add association preference step (step 4)", status: "done", date: "2026-03-08", notes: "3-way chip: No Preference / Yes / No. Pets moved to step 5." },
      { id: "PM-101", title: "Preferences screen redesign: section reorder, save container, bigger toggles", status: "done", date: "2026-03-08", notes: "Order: Budget→Property→Location→Features→Pets→Association→Save. Switch 1.5x scale via LAYOUT.switch." },
      { id: "PM-102", title: "List view: bigger cards with address+city, infinite scroll prefetch buffer", status: "done", date: "2026-03-08", notes: "ListingCard image 120→140, price 16→14px, address includes city. useListings prefetch buffer pattern — next page pre-loaded silently, flushes instantly on scroll." },
      { id: "PM-103", title: "Owner UX batch 3: address label, mandatory fields, description styling", status: "done", date: "2026-03-09", notes: "Rental Property Address label, Year Built + Sq/Ft mandatory, description char counter (green/red at 500), Describe Your Rental Property label" },
      { id: "PM-104", title: "Owner UX: lease term chips, native date picker, HOA yes/no chips", status: "done", date: "2026-03-09", notes: "3/6/12 month chip selector, @react-native-community/datetimepicker for available date, HOA binary chips replacing dollar field" },
      { id: "PM-105", title: "Owner UX: remove pets Unknown option, global Toggle component", status: "done", date: "2026-03-09", notes: "Reusable Toggle.js (green on/slate off), replaces all Switch instances across app" },
      { id: "PM-106", title: "Owner UX: dual photo upload buttons + desktop upload link feature", status: "done", date: "2026-03-09", notes: "Add Photos from Phone + Upload from Desktop/Laptop side-by-side. Magic link email → web drag-drop uploader → Realtime sync back to mobile" },
      { id: "PM-107", title: "Sharp photo processing pipeline (server-side)", status: "done", date: "2026-03-09", notes: "Resize 1600px max + 400px thumbnail, WebP 80% quality, EXIF strip. ~90% storage reduction. maxDuration=60s" },
      { id: "PM-108", title: "Owner contact step: preference selector + auto-populate + phone formatting", status: "done", date: "2026-03-09", notes: "Email/Phone/Both chips, email auto-populated from auth, phone auto-formats (XXX) XXX-XXXX, 10-digit validation, email format validation on blur" },
      { id: "PM-109", title: "Listing confirmation code + email on submit", status: "done", date: "2026-03-09", notes: "PM-XXXXXX code generated on activation, stored in confirmation_code column (unique index). Branded email with listing summary sent via Resend. Migration 029+030." },
      { id: "PM-110", title: "Fix listings_status_check constraint (pending_payment → active)", status: "done", date: "2026-03-09", notes: "DB CHECK only allows draft/active/expired/leased/archived. Stripe deferred, submit as active." },
      { id: "PM-111", title: "Migration 028: association_preferred column on tenant_preferences", status: "done", date: "2026-03-09", notes: "Was missing despite backlog showing done — preference only survived in AsyncStorage" },
      { id: "PM-112", title: "My Listings card polish: white borders, frost button, status/views row, add listing button", status: "done", date: "2026-03-10", notes: "Action buttons with white borders, frost arrow for Nearby Rentals, status badge + view count on own row, +Add Additional Rental Listing header button" },
      { id: "PM-113", title: "Unique view tracking: listing_views table with deduplication", status: "done", date: "2026-03-10", notes: "Migration 031. UNIQUE(listing_id, user_id) constraint, upsert on view, only counts active listings. Replaces naive view_count." },
      { id: "PM-114", title: "Price edit modal: auto-populate, placeholder fix, wider card", status: "done", date: "2026-03-10", notes: "useEffect resets field on open, placeholder '0', reduced font size, 92% width" },
      { id: "PM-115", title: "Edit listing photo page cleanup: button style, delete confirmation, spacing", status: "done", date: "2026-03-10", notes: "Match create wizard buttons, alert() before delete, Replace All Photos at bottom, marginBottom 90 fix, readable photo count" },
      { id: "PM-116", title: "Brand color update: brandOrange → #F59E0B (star gold), deepOrange preserved", status: "done", date: "2026-03-10", notes: "All orange text instances updated across app" },
      { id: "PM-117", title: "Google geocoding dual-key setup (mobile + server keys)", status: "done", date: "2026-03-10", notes: "GOOGLE_SERVER_GEOCODING_KEY for server-side geocoding (unrestricted). Mobile key remains Android-restricted." },
      { id: "PM-118", title: "Nearby Rentals: free access gate, redesigned UI, owner card integration", status: "done", date: "2026-03-10", notes: "Removed expires_at gate (Stripe deferred). Owner property as first card. Filter rows split (Radius, Beds). Map/grid toggle. Fixed-height cards with city." },
      { id: "PM-119", title: "Bridge sync street name fix: include directional prefixes/suffixes", status: "done", date: "2026-03-10", notes: "StreetDirPrefix + StreetName + StreetSuffix + StreetDirSuffix. Fixed 11,400+ MLS listings missing NE/SE/SW/NW." },
      { id: "PM-120", title: "Google Places short_name for abbreviated street addresses", status: "done", date: "2026-03-10", notes: "Owner onboarding uses short_name (SE vs Southeast)" },
      { id: "PM-121", title: "Nearby Rentals: beds filter 3+ logic, baths filter removed, compact card format", status: "done", date: "2026-03-10", notes: "Exact match for 1-2 beds, >= for 3+. Cards show '3b · 2ba · 1,500 sqft'. SQL function bathrooms_total fixed to numeric type." },
    ],
  },
  {
    category: "Ready to Build — Admin Dashboard",
    items: [
      { id: "T02", title: "Extract AdminLayout shell from monolith", status: "done", date: "2026-03-04", notes: "dashboard.js → shell (277 lines) + shared.js + demo-data.js" },
      { id: "T03", title: "Extract panels into separate files under panels/", status: "done", date: "2026-03-04", notes: "11 panel files in app/admin/panels/, zero behavior changes" },
      { id: "T04", title: "Wire Overview panel to real Supabase data", status: "done", date: "2026-03-07", notes: "Live stats, sync logs, owner listing signup, site_config persistence" },
      { id: "T05", title: "Wire Feeds panel to real sync_logs data", status: "pending", notes: "sync_logs table exists, UI still hardcoded" },
      { id: "T06", title: "Wire Listings panel to real data", status: "pending", notes: "Admin listings API exists, panel needs rewiring" },
      { id: "T07", title: "Wire PadScore panel to Supabase", status: "pending", notes: "padscore_configs table exists, need API + wire save" },
      { id: "T08", title: "Wire Billing panel to real data", status: "pending", notes: "Billing tables exist, panel is stub" },
      { id: "T-WL", title: "Wire Waitlist panel to real data", status: "pending", notes: "Still using DEMO data" },
      { id: "T-SM", title: "Splash message system (site_config table + Overview card + mobile display)", status: "pending", notes: "Admin-editable message on owner/tenant empty states" },
      { id: "T-RL", title: "Enable RLS on profiles table", status: "pending", notes: "Users read own row, admins read all" },
      { id: "T-UR", title: "Unify role source of truth (profiles.role for all users)", status: "pending", notes: "Mobile currently reads user_metadata.role — needs migration to profiles" },
    ],
  },
  {
    category: "Ready to Build — Mobile App",
    items: [
      { id: "T-SL", title: "Shareable listing links (share button + public web page + OG tags + store badges)", status: "done", date: "2026-03-07", notes: "Share API on mobile, public listing page at padmagnet.com/listing/[id], OG meta for link previews, app store badges" },
      { id: "T-ME", title: "Mobile listing edit screen", status: "pending", notes: "PUT API exists, no mobile UI yet" },
      { id: "T-OF", title: "Owner create form: add 5 new owner fields", status: "pending", notes: "owner_special_comments, owner_application_link, owner_pet_policy_details, owner_utilities_included, owner_showing_instructions — API accepts them, no mobile UI yet" },
      { id: "T21", title: "Boost indicator badge on swipe cards", status: "pending", notes: "Subtle \"Boosted\" badge on boosted listings" },
    ],
  },
  {
    category: "Phase 2 — Owner Web Dashboard (/dashboard)",
    items: [
      { id: "T09", title: "Owner dashboard shell at /dashboard", status: "pending", notes: "Layout, auth, routes" },
      { id: "T10", title: "Owner listings management page", status: "pending", notes: "Web equivalent of mobile listings" },
      { id: "T11", title: "Owner listing detail with tabbed interface", status: "pending", notes: "Details, Calendar, Documents, Analytics tabs" },
      { id: "T12", title: "Calendar/availability/tour scheduling", status: "pending", notes: "DB tables exist, need API + UI" },
      { id: "T13", title: "Documents upload and send", status: "pending", notes: "DB table + storage bucket exist" },
      { id: "T15", title: "Email template editor (TipTap)", status: "pending", notes: "DB table exists" },
      { id: "T16", title: "Boost purchase flow for owners", status: "pending", notes: "Owner-facing boost API" },
      { id: "T18", title: "Owner analytics page", status: "pending", notes: "view_count works, need standalone page" },
    ],
  },
  {
    category: "Phase 3 — Mobile Polish",
    items: [
      { id: "T19", title: "Tenant tour request UI", status: "pending", notes: "Request Tour button + time slot picker" },
      { id: "T20", title: "Document viewer", status: "pending", notes: "PDF viewing + viewed_at tracking" },
      { id: "T22", title: "Owner billing screen", status: "pending", notes: "Wire up to purchase history + Stripe portal" },
      { id: "T23", title: "Multichannel message indicators", status: "pending", notes: "SMS/email/in-app channel icons" },
    ],
  },
  {
    category: "Blocked / Deferred",
    items: [
      { id: "T14", title: "Twilio multichannel messaging", status: "blocked", notes: "Twilio account setup required" },
      { id: "T17", title: "Owner billing UI (Stripe)", status: "blocked", notes: "Corporate entity + banking required" },
      { id: "T-ST", title: "Stripe activation (all payment flows)", status: "blocked", notes: "Corporate entity + banking required" },
      { id: "T-BR", title: "Bridge IDX sync", status: "done", date: "2026-03-07", notes: "Miami IDX feed live — 5-county filter (St Lucie to Miami-Dade), ~11,400 active rental listings" },
      { id: "T-EA", title: "EAS production build", status: "pending", notes: "Dev build working. Production build needed for Play Store submission. Will need SHA-1 fingerprint for Google Maps key restriction." },
      { id: "T-AS", title: "App Store / Play Store submission", status: "deferred", notes: "After EAS build" },
      { id: "T-AP", title: "Revisit tenant product app_path values", status: "deferred", notes: "After tenant pages defined" },
      { id: "T-GM", title: "Google Maps: fresh GCP project + new API key + fix blank tiles", status: "done", date: "2026-03-08", notes: "New GCP project 'padmagnet-maps' under floridapm.net. Key unrestricted for now — TODO: restrict to Maps SDK + Geocoding API, add $1/month budget alert, add Android app restriction after production EAS build." },
      { id: "T-AY", title: "Add AssociationYN to Bridge sync for definitive association detection", status: "deferred", notes: "Currently using hoa_fee > 0 as proxy — add RESO field when Bridge access is live" },
      { id: "T-IS", title: "Incremental sync via ModificationTimestamp (10K+ scaling)", status: "deferred", notes: "Bridge $skip limit is 10K. Switch to timestamp-based delta sync when dataset grows. Weekly full reconciliation for deactivations." },
    ],
  },
];
