// ╔══════════════════════════════════════════════════════════════════╗
// ║  PADMAGNET PROJECT BACKLOG                                      ║
// ║                                                                 ║
// ║  Single source of truth for project tasks.                      ║
// ║  Claude updates this file after each session.                   ║
// ║  Status: done | in-progress | pending | blocked | deferred      ║
// ╚══════════════════════════════════════════════════════════════════╝

export const BACKLOG = [
  {
    category: "Completed — Foundation & Core",
    items: [
      { id: "T01", title: "Run migrations 009-020 (landlord workflow, billing, storage, etc.)", status: "done", date: "2026-03-03" },
      { id: "PM-09", title: "Google Geocoding key configured", status: "done", date: "2026-03-03" },
      { id: "PM-10", title: "Photo upload to Supabase Storage", status: "done", date: "2026-03-03" },
      { id: "PM-11", title: "PadScore lease_too_short check (server + client)", status: "done", date: "2026-03-03" },
      { id: "PM-12", title: "Stripe API routes (checkout, webhook, renew) — code written, not wired", status: "done", date: "2026-03-03" },
      { id: "PM-13", title: "Cron jobs: listing expiration + expiry emails", status: "done", date: "2026-03-03" },
      { id: "PM-14", title: "Mobile owner create flow (8-step wizard)", status: "done", date: "2026-03-03" },
      { id: "PM-15", title: "Mobile listing preview + relist screens", status: "done", date: "2026-03-03" },
      { id: "PM-16", title: "Auth flow workarounds for Expo Go (magic link, deep links)", status: "done", date: "2026-03-03" },
      { id: "PM-17", title: "SMTP fix (Resend key rotation in Supabase Auth)", status: "done", date: "2026-03-03" },
      { id: "PM-18", title: "Design system unification (AuthHeader, app-theme.css, COLORS)", status: "done", date: "2026-03-02" },
    ],
  },
  {
    category: "Completed — Recent Sessions",
    items: [
      { id: "PM-01", title: "Product display flow — API, hook, ProductCard, Services screen", status: "done", date: "2026-03-04" },
      { id: "PM-02", title: "Fix product data freshness (Next.js fetch cache + no-store)", status: "done", date: "2026-03-04" },
      { id: "PM-03", title: "Supabase Realtime on products table", status: "done", date: "2026-03-04" },
      { id: "PM-04", title: "Products admin panel — audience split, hard delete, inline edit", status: "done", date: "2026-03-03" },
      { id: "PM-05", title: "Admin dashboard — standardize Listings + Audit panels to AdminTable", status: "done", date: "2026-03-03" },
      { id: "PM-06", title: "Owner tab reorder (Listings > Services > Messages > Profile)", status: "done", date: "2026-03-04" },
      { id: "PM-07", title: "Dashboard: Wired to App column, Last Modified column, updated_at trigger", status: "done", date: "2026-03-04" },
      { id: "PM-08", title: "Mobile \\n line break rendering in ProductCard", status: "done", date: "2026-03-04" },
      { id: "PM-19", title: "Backlog dashboard panel (data file + UI + animated sidebar button)", status: "done", date: "2026-03-04" },
      { id: "PM-20", title: "Fix profiles.role default from admin to tenant", status: "done", date: "2026-03-04" },
      { id: "PM-21", title: "Fix test user roles (info@ → tenant, maintenance@ → owner)", status: "done", date: "2026-03-04" },
      { id: "PM-22", title: "Admin login: forgot password flow (implicit auth, Resend email)", status: "done", date: "2026-03-04" },
      { id: "PM-23", title: "Admin password reset via Management API", status: "done", date: "2026-03-04" },
      { id: "PM-24", title: "Role-gated admin middleware (profiles.role check)", status: "done", date: "2026-03-04" },
      { id: "PM-25", title: "Fix PKCE recovery flow (server-side code exchange + implicit fallback)", status: "done", date: "2026-03-04" },
      { id: "PM-26", title: "Waitlist role label landlord → owner (DB + landing page)", status: "done", date: "2026-03-04" },
      { id: "PM-27", title: "Delete orphaned chris@floridapm.net (auth + waitlist)", status: "done", date: "2026-03-04" },
      { id: "PM-28", title: "Replace geocode API with local service-area autocomplete in ZonePicker", status: "done", date: "2026-03-05", notes: "Static city/zip data for 5 counties, local filtering, no API calls" },
      { id: "PM-29", title: "Require at least 1 zone in onboarding step 2", status: "done", date: "2026-03-05" },
      { id: "PM-30", title: "Onboarding overhaul: back pill, bigger logo, new copy, remove skip", status: "done", date: "2026-03-05" },
      { id: "PM-31", title: "Onboarding step resumption (persists to AsyncStorage)", status: "done", date: "2026-03-05" },
      { id: "PM-32", title: "Fix VirtualizedList nesting error in ZonePicker", status: "done", date: "2026-03-05" },
      { id: "PM-33", title: "Fix keyboard covering zone search on onboarding step 2", status: "done", date: "2026-03-05" },
      { id: "PM-34", title: "Property type onboarding step (7 types, chip selectors, PadScore integration)", status: "done", date: "2026-03-05" },
      { id: "PM-35", title: "Text-based logo on welcome screen (white Pad + orange Magnet)", status: "done", date: "2026-03-05" },
      { id: "PM-36", title: "Back pill moved to upper-left + Back text link restored on all steps", status: "done", date: "2026-03-05" },
      { id: "PM-37", title: "Profile button renamed to PadScore™ Preferences", status: "done", date: "2026-03-05" },
      { id: "PM-38", title: "Property types list synced across onboarding, preferences, owner create", status: "done", date: "2026-03-05" },
      { id: "PM-39", title: "Remove Min Budget, Min Lease, Max HOA from tenant preferences UI", status: "done", date: "2026-03-05", notes: "DB columns kept, just hidden from UI" },
      { id: "PM-40", title: "Add association_preferred column + Association chip selector in preferences", status: "done", date: "2026-03-05", notes: "NULL=no pref, true=prefer, false=avoid; 50pt PadScore penalty on mismatch" },
      { id: "PM-41", title: "Replace hoa_mismatch with association_mismatch in PadScore (server+client+admin)", status: "done", date: "2026-03-05", notes: "Uses hoa_fee > 0 as proxy for association until AssociationYN from Bridge" },
      { id: "PM-42", title: "Update preferences footer text + location label", status: "done", date: "2026-03-05" },
      { id: "PM-43", title: "Fix Profile tab crash (move GestureHandlerRootView to root layout)", status: "done", date: "2026-03-05", notes: "Native crash caused by gesture handler scoped to swipe tab only" },
      { id: "PM-44", title: "Swipe undo system (DELETE API + 5s undo button + haptics)", status: "done", date: "2026-03-05", notes: "Single swipe delete + bulk reset endpoints, undo button auto-dismisses" },
      { id: "PM-45", title: "Saved/Passed toggle on Saved tab with remove + reconsider actions", status: "done", date: "2026-03-05", notes: "Pill-style toggle, remove from Saved, reconsider from Passed — both return listing to deck" },
      { id: "PM-46", title: "Reset Swipe History option on Profile screen", status: "done", date: "2026-03-05", notes: "Danger-styled menu item with confirmation, bulk deletes all swipes" },
      { id: "PM-47", title: "Fix swipes not saving — disable Next.js fetch cache on Supabase client", status: "done", date: "2026-03-06", notes: "Next.js 14 cached PostgREST responses by default; stale seed data caused FK violations on swipe POST" },
      { id: "PM-48", title: "Surface swipe errors via Alert instead of silent console.warn", status: "done", date: "2026-03-06", notes: "Also fixed apiFetch header merge order to prevent auth header clobbering" },
      { id: "PM-49", title: "Delete test seed file + improve empty state messaging", status: "done", date: "2026-03-06", notes: "Removed seed_test_listings.sql; updated empty states to 'We don't have homes that fit your search yet'" },
      { id: "PM-50", title: "PadScore badge: percentage display, white text, blue bubble", status: "done", date: "2026-03-06" },
      { id: "PM-51", title: "Swipe header: Pad (white) + Magnet (orange) branded logo", status: "done", date: "2026-03-06" },
      { id: "PM-52", title: "Explicit Stack.Screen declarations for all routes in root layout", status: "done", date: "2026-03-06", notes: "Prevents Expo Router auto-discovery issues with owner/, listing/, etc." },
      { id: "PM-53", title: "Unified alerts: migrate all tenant screens from native Alert to custom useAlert", status: "done", date: "2026-03-06", notes: "saved.js, profile.js, useSwipe.js now match owner screen styling" },
      { id: "PM-54", title: "Swipe action buttons: trash icon for skip, 'More Info' label for detail", status: "done", date: "2026-03-06" },
      { id: "PM-55", title: "Saved screen overhaul: Loved/Trash tabs with heart/trash icons + border outline active indicator", status: "done", date: "2026-03-06", notes: "Frosted glass trash button on cards, FontAwesome icons on tabs" },
      { id: "PM-56", title: "Await recordSwipe in handleSwipe to prevent silent save failures", status: "done", date: "2026-03-06", notes: "Card restored to deck on API failure instead of vanishing" },
      { id: "PM-57", title: "Saved page re-fetches on tab focus via useFocusEffect", status: "done", date: "2026-03-06" },
      { id: "PM-58", title: "Reset deck button on swipe screen header", status: "done", date: "2026-03-06", notes: "Confirmation alert, clears all swipes, reloads deck" },
      { id: "PM-59", title: "Swipe reset direction: removed listings return to bottom of deck", status: "done", date: "2026-03-06", notes: "PATCH/POST with direction='reset', listings API sorts _reseen to bottom" },
      { id: "PM-60", title: "Fix Bridge sync missing photos: drop $select to get Media navigation property", status: "done", date: "2026-03-06", notes: "OData $select suppresses navigation properties even with $expand; fetching all fields resolves it" },
      { id: "PM-61", title: "Beach/palm tree placeholder for listings without photos", status: "done", date: "2026-03-06", notes: "SwipeCard, ListingCard, PhotoGallery — deep ocean blue bg, faded emoji, white 'Listing Photo Coming Soon' overlay" },
      { id: "PM-62", title: "Fix deck not refreshing on reset button press", status: "done", date: "2026-03-06", notes: "refresh() didn't clear listings array — deck looked unchanged. Now clears to show loading spinner before re-fetch" },
      { id: "PM-63", title: "Display field config system — DB table, admin panel, config-driven ListingInfo", status: "done", date: "2026-03-06", notes: "Migration 022: display_field_configs (26 rows) + 5 owner columns. Admin CRUD panel. ListingInfo.js refactored to render from config. Bridge sync now captures PublicRemarks, pool, parking, virtual_tour_url." },
      { id: "PM-64", title: "Remove Treasure Coast city filter, expand to 5-county coverage", status: "done", date: "2026-03-07", notes: "Bridge sync now filters by county (St Lucie, Martin, Palm Beach, Broward, Miami-Dade) with 30-day freshness window. ~11,400 listings." },
      { id: "PM-65", title: "Wire Overview panel to live Supabase data", status: "done", date: "2026-03-07", notes: "4 stat cards, feed health, sync logs, owner listing signup — all live. Demo data removed from OverviewPanel." },
      { id: "PM-66", title: "Admin header: user name bubble + remove county badge", status: "done", date: "2026-03-07" },
      { id: "PM-67", title: "site_config table + /api/admin/config for persistent admin fields", status: "done", date: "2026-03-07", notes: "Bridge portal URL and IDX notes persist across sessions" },
      { id: "PM-68", title: "Bridge sync: per-county fetch + stream-upsert + updated_at deactivation", status: "done", date: "2026-03-07", notes: "Handles 15K+ listings, stays under Bridge 10K $skip limit, Vercel Pro 300s timeout" },
      { id: "PM-69", title: "Mobile: auto-refresh listings on app foreground (AppState listener)", status: "done", date: "2026-03-07", notes: "useListings.js re-fetches on AppState 'active', preserves saved cards" },
      { id: "PM-70", title: "Email footer updated to PadMagnet.com tagline", status: "done", date: "2026-03-07" },
      { id: "PM-71", title: "Photo gallery progress bar (replace dot indicators)", status: "done", date: "2026-03-07", notes: "6px bar at bottom of photo gallery, scales with photo count" },
      { id: "PM-72", title: "Fix duplicate key error on listing loadMore", status: "done", date: "2026-03-07", notes: "Set-based dedup in useListings append" },
      { id: "PM-73", title: "Swipe refresh button: move left of logo, feed-only refresh (no swipe deletion)", status: "done", date: "2026-03-07" },
      { id: "PM-74", title: "Saved screen: trash icon moves card to Trash tab, reconsider uses DELETE", status: "done", date: "2026-03-07", notes: "Fixed swipes_direction_check constraint violation" },
      { id: "PM-75", title: "Restore All button on Trash tab (direction=left only, preserves Loved)", status: "done", date: "2026-03-07", notes: "API updated to accept ?direction= param for selective reset" },
      { id: "PM-76", title: "Remove undo swipe button from swipe screen", status: "done", date: "2026-03-07" },
      { id: "PM-77", title: "Tinder-style swipe gestures on card stack", status: "done", date: "2026-03-07", notes: "Root cause: overflow:hidden on gesture target blocked Android touches. Fix: separate gesture target (no overflow) from visual card. Added velocity-based swipe detection." },
      { id: "PM-78", title: "Swipe overlay icons: heart (save) + trash (skip) in circles, mid-photo placement", status: "done", date: "2026-03-07" },
      { id: "PM-79", title: "Back card offset (9px left, 15px down) for visual deck cue", status: "done", date: "2026-03-07" },
      { id: "PM-80", title: "Empty state icon color set to white, Trash/Loved empty text updated", status: "done", date: "2026-03-07" },
      { id: "PM-81", title: "Fix CardStack render-phase state update (prefetch moved to useEffect)", status: "done", date: "2026-03-07" },
      { id: "PM-82", title: "Rename Reconsider button to Un-Trash", status: "done", date: "2026-03-07" },
      { id: "PM-83", title: "Swipe card wiggle hint on initial app load", status: "done", date: "2026-03-07", notes: "Subtle 8px horizontal shake, fires once via useRef flag" },
      { id: "PM-84", title: "Personalized intro text above card deck with user's first name + PadScore branding", status: "done", date: "2026-03-07" },
      { id: "PM-85", title: "Compact swipe card: remove MLS office, merge city into address, 70/30 photo/info split", status: "done", date: "2026-03-07" },
      { id: "PM-86", title: "Card height reduced to 58% screen for responsive layout on all devices", status: "done", date: "2026-03-07" },
      { id: "PM-87", title: "Fix FontAwesome tab bar icons (font preloading via useFonts splash gate)", status: "done", date: "2026-03-07", notes: "Icons rendered as Unicode before font loaded — added ...FontAwesome.font to useFonts() in root layout" },
      { id: "PM-88", title: "More Info button → standard info icon with white border styling", status: "done", date: "2026-03-07" },
      { id: "PM-89", title: "Shareable listing links: share button + public web page + OG tags + store badges", status: "done", date: "2026-03-07", notes: "Share.share() on mobile, public page at /listing/[id] with OG meta, app store download badges" },
      { id: "PM-90", title: "Share button design: icon+label pill (40x80, accent border, rounded)", status: "done", date: "2026-03-07" },
      { id: "PM-91", title: "Saved screen tab styling: bright white active text, dimmed slate inactive", status: "done", date: "2026-03-07" },
      { id: "PM-92", title: "EAS development build setup (replaces Expo Go for native module support)", status: "done", date: "2026-03-08", notes: "EAS project @cmlundstrom/padmagnet, dev profile builds APK with native modules (Google Maps, expo-navigation-bar)" },
      { id: "PM-93", title: "Google Maps working on Android via EAS dev build", status: "done", date: "2026-03-08", notes: "Root cause: Expo Go can't inject Maps API key into native binary. Fix: EAS dev build + react-native-maps plugin + PROVIDER_GOOGLE. Also fixed HTTP referer restriction on API key." },
      { id: "PM-94", title: "Fix settings route warning (add settings/_layout.js)", status: "done", date: "2026-03-08" },
      { id: "PM-95", title: "Fix tab bar hidden behind Android system nav bar (edge-to-edge mode)", status: "done", date: "2026-03-08", notes: "SafeAreaView edges={['bottom']} on tab layouts. expo-navigation-bar for system nav color match (pending next build)." },
      { id: "PM-96", title: "Draggable column reordering on AdminTable + per-role field visibility", status: "done", date: "2026-03-08", notes: "@dnd-kit on header cells, localStorage persistence, visible_owner column on display_field_configs" },
      { id: "PM-97", title: "Tab bar spacing: marginBottom -21 + expo-navigation-bar color match", status: "done", date: "2026-03-08", notes: "Recovers ~20px of screen real estate on Android" },
      { id: "PM-98", title: "Google Maps API key rotated to EAS Secret", status: "done", date: "2026-03-08", notes: "Old key deleted, new key in EAS Secret + local envs only, no hardcoded values in repo" },
      { id: "PM-99", title: "PadScore association fix: one-directional penalty only", status: "done", date: "2026-03-08", notes: "Only penalize when tenant says No + property has HOA. Yes and No Preference = zero impact." },
      { id: "PM-100", title: "Onboarding: add association preference step (step 4)", status: "done", date: "2026-03-08", notes: "3-way chip: No Preference / Yes / No. Pets moved to step 5." },
      { id: "PM-101", title: "Preferences screen redesign: section reorder, save container, bigger toggles", status: "done", date: "2026-03-08", notes: "Order: Budget→Property→Location→Features→Pets→Association→Save. Switch 1.5x scale via LAYOUT.switch." },
      { id: "PM-102", title: "List view: bigger cards with address+city, infinite scroll prefetch buffer", status: "done", date: "2026-03-08", notes: "ListingCard image 120→140, price 16→14px, address includes city. useListings prefetch buffer pattern — next page pre-loaded silently, flushes instantly on scroll." },
      { id: "PM-103", title: "Owner UX batch 3: address label, mandatory fields, description styling", status: "done", date: "2026-03-09", notes: "Rental Property Address label, Year Built + Sq/Ft mandatory, description char counter (green/red at 500), Describe Your Rental Property label" },
      { id: "PM-104", title: "Owner UX: lease term chips, native date picker, HOA yes/no chips", status: "done", date: "2026-03-09", notes: "3/6/12 month chip selector, @react-native-community/datetimepicker for available date, HOA binary chips replacing dollar field" },
      { id: "PM-105", title: "Owner UX: remove pets Unknown option, global Toggle component", status: "done", date: "2026-03-09", notes: "Reusable Toggle.js (green on/slate off), replaces all Switch instances across app" },
      { id: "PM-106", title: "Owner UX: dual photo upload buttons + desktop upload link feature", status: "done", date: "2026-03-09", notes: "Add Photos from Phone + Upload from Desktop/Laptop side-by-side. Magic link email → web drag-drop uploader → Realtime sync back to mobile" },
      { id: "PM-107", title: "Sharp photo processing pipeline (server-side)", status: "done", date: "2026-03-09", notes: "Resize 1600px max + 400px thumbnail, WebP 80% quality, EXIF strip. ~90% storage reduction. maxDuration=60s" },
      { id: "PM-108", title: "Owner contact step: preference selector + auto-populate + phone formatting", status: "done", date: "2026-03-09", notes: "Email/Phone/Both chips, email auto-populated from auth, phone auto-formats (XXX) XXX-XXXX, 10-digit validation, email format validation on blur" },
      { id: "PM-109", title: "Listing confirmation code + email on submit", status: "done", date: "2026-03-09", notes: "PM-XXXXXX code generated on activation, stored in confirmation_code column (unique index). Branded email with listing summary sent via Resend. Migration 029+030." },
      { id: "PM-110", title: "Fix listings_status_check constraint (pending_payment → active)", status: "done", date: "2026-03-09", notes: "DB CHECK only allows draft/active/expired/leased/archived. Stripe deferred, submit as active." },
      { id: "PM-111", title: "Migration 028: association_preferred column on tenant_preferences", status: "done", date: "2026-03-09", notes: "Was missing despite backlog showing done — preference only survived in AsyncStorage" },
      { id: "PM-112", title: "My Listings card polish: white borders, frost button, status/views row, add listing button", status: "done", date: "2026-03-10", notes: "Action buttons with white borders, frost arrow for Nearby Rentals, status badge + view count on own row, +Add Additional Rental Listing header button" },
      { id: "PM-113", title: "Unique view tracking: listing_views table with deduplication", status: "done", date: "2026-03-10", notes: "Migration 031. UNIQUE(listing_id, user_id) constraint, upsert on view, only counts active listings. Replaces naive view_count." },
      { id: "PM-114", title: "Price edit modal: auto-populate, placeholder fix, wider card", status: "done", date: "2026-03-10", notes: "useEffect resets field on open, placeholder '0', reduced font size, 92% width" },
      { id: "PM-115", title: "Edit listing photo page cleanup: button style, delete confirmation, spacing", status: "done", date: "2026-03-10", notes: "Match create wizard buttons, alert() before delete, Replace All Photos at bottom, marginBottom 90 fix, readable photo count" },
      { id: "PM-116", title: "Brand color update: brandOrange → #F59E0B (star gold), deepOrange preserved", status: "done", date: "2026-03-10", notes: "All orange text instances updated across app" },
      { id: "PM-117", title: "Google geocoding dual-key setup (mobile + server keys)", status: "done", date: "2026-03-10", notes: "GOOGLE_SERVER_GEOCODING_KEY for server-side geocoding (unrestricted). Mobile key remains Android-restricted." },
      { id: "PM-118", title: "Nearby Rentals: free access gate, redesigned UI, owner card integration", status: "done", date: "2026-03-10", notes: "Removed expires_at gate (Stripe deferred). Owner property as first card. Filter rows split (Radius, Beds). Map/grid toggle. Fixed-height cards with city." },
      { id: "PM-119", title: "Bridge sync street name fix: include directional prefixes/suffixes", status: "done", date: "2026-03-10", notes: "StreetDirPrefix + StreetName + StreetSuffix + StreetDirSuffix. Fixed 11,400+ MLS listings missing NE/SE/SW/NW." },
      { id: "PM-120", title: "Google Places short_name for abbreviated street addresses", status: "done", date: "2026-03-10", notes: "Owner onboarding uses short_name (SE vs Southeast)" },
      { id: "PM-121", title: "Nearby Rentals: beds filter 3+ logic, baths filter removed, compact card format", status: "done", date: "2026-03-10", notes: "Exact match for 1-2 beds, >= for 3+. Cards show '3b · 2ba · 1,500 sqft'. SQL function bathrooms_total fixed to numeric type." },
      { id: "PM-122", title: "Step 8: Fix tenant_active_listings view security", status: "done", date: "2026-03-12", notes: "security_invoker=true, added is_active check to owner branch, SELECT-only permissions. Supabase Security Advisor: 0 alerts." },
      { id: "PM-123", title: "Profile editing: shared Edit Profile screen for both roles", status: "done", date: "2026-03-12", notes: "ProfileCard with built-in Edit button, display name/email/phone editing, phone auto-format, email change triggers server-side OTP confirmation" },
      { id: "PM-124", title: "Email change confirmation flow (server-side OTP)", status: "done", date: "2026-03-12", notes: "Custom /auth/confirm route with service role client, verifyOtp + getUserById for definitive email, profiles.email sync, branded /email-confirmed page. Single confirmation (new email only)." },
      { id: "PM-125", title: "Global trash cleanup: drop 16 orphaned tables, 3 functions, consolidate triggers", status: "done", date: "2026-03-12", notes: "Migration 036. Tables: 42→25. Consolidated 3 duplicate updated_at functions into 1." },
      { id: "PM-126", title: "Code cleanup: stale user_metadata refs, landlord→owner text, ROLE_LABELS consolidation", status: "done", date: "2026-03-12", notes: "swipe.js/routing.js/create.js now read profiles table. All user-facing 'landlord' text replaced. ROLE_LABELS shared via constants/roles.js." },
      { id: "PM-127", title: "Brand identity refresh: new icon set across all platforms", status: "done", date: "2026-03-12", notes: "4 icon variants (full color, navy mono, orange mono, white-on-orange). Web favicons, OG image, mobile app icon, splash, Android adaptive icons, admin dashboard. Old icons archived in /old/ folders." },
      { id: "PM-128", title: "New header logo with updated tagline", status: "done", date: "2026-03-12", notes: "Icon + PadMagnet wordmark + 'Find Your Perfect Rental with PadScore™'. Pad=navy, Magnet=deepOrange." },
      { id: "PM-129", title: "Landing page nav bar darkened for header contrast", status: "done", date: "2026-03-12", notes: "Warm cream rgba(237,228,220,0.85) with blur, visible at all times not just on scroll" },
      { id: "PM-130", title: "Fix PadMagnet brand text color: deepOrange for Magnet across all screens", status: "done", date: "2026-03-12", notes: "4 mobile screens were using soft brandOrange (#F59E0B) instead of bold deepOrange (#F95E0C). Web was already correct." },
      { id: "PM-131", title: "Admin dashboard: orange icon variant + Pad/Magnet color split", status: "done", date: "2026-03-12", notes: "White-on-orange icon for dark sidebar, Magnet text in deepOrange" },
      { id: "PM-132", title: "Geo-fence: bounding-box pre-filter on listings API", status: "done", date: "2026-03-12", notes: "computeGeoBounds() computes lat/lng box from tenant search zones × 1.5 buffer. Fixes Stuart tenant seeing Miami listings." },
      { id: "PM-133", title: "Per-zone radius chips on ZonePicker (3/7/10/15 mi)", status: "done", date: "2026-03-12", notes: "Each zone has its own radius_miles. Default 10mi. Chips use global CHIP_STYLES." },
      { id: "PM-134", title: "Preferences screen auto-save redesign", status: "done", date: "2026-03-12", notes: "Discrete values save immediately, text debounces 1.5s. Floating 'Start Swiping' button with flush-before-nav. Save status indicator." },
      { id: "PM-135", title: "Swipe deck refresh on preferences change", status: "done", date: "2026-03-12", notes: "router.replace with ?refresh=true param triggers fresh fetch in useListings." },
      { id: "PM-136", title: "Fix empty swipe deck on hot reload", status: "done", date: "2026-03-12", notes: "Three-layer fix: session gate, auth retry with backoff, fetchingRef reset. Fast Refresh preserves stale refs." },
      { id: "PM-137", title: "NoPhotoPlaceholder component + PadScore no_photos penalty", status: "done", date: "2026-03-12", notes: "Shared component (3 sizes), navy gradient + camera icon. -35pt PadScore penalty. Replaces emoji placeholders across 5 screens." },
      { id: "PM-138", title: "Price change tracking: DB trigger + PadScore bonus + visual badge", status: "done", date: "2026-03-13", notes: "Migration 037: previous_list_price + price_changed_at + Postgres trigger. +15 PadScore bonus for drops within 7 days. Green 'Price Drop' badge on SwipeCard + ListingCard." },
      { id: "PM-139", title: "Admin PadScorePanel: add no_photos + price_drop_recent weights", status: "done", date: "2026-03-13", notes: "New 'Presentation & Pricing' group. Preview scoring updated. 17 total weights." },
      { id: "PM-140", title: "Tenant grid card: split address/city lines, bold city, taller image", status: "done", date: "2026-03-13", notes: "ListingCard image 140→150px, city on separate bold line. Fixes city cutoff." },
      { id: "PM-141", title: "Save heart on listing detail screen", status: "done", date: "2026-03-13", notes: "Floating green heart FAB at 67% top. GlossyHeart (saved) / heart-o (unsaved). Pulse + burst animation (3 mini hearts). Pre-fills from Saved screen via context param." },
      { id: "PM-142", title: "Swipes API: single-listing save check via ?listing_id= param", status: "done", date: "2026-03-13", notes: "Lightweight .maybeSingle() query for detail screen save state." },
      { id: "PM-143", title: "Communications system: migration 038 (schema, RPC, templates, phone mappings)", status: "done", date: "2026-03-13", notes: "External agent columns, nullable sender_id, delivery queue, webhook logs, message templates, phone mappings, increment_unread RPC, Realtime on conversations." },
      { id: "PM-144", title: "Notification routing: lib/sms.js, lib/push.js, lib/notify.js", status: "done", date: "2026-03-13", notes: "Twilio SMS + Expo push + email helpers. Immediate-send with retry queue fallback. notifyRecipient (internal) and notifyExternalAgent (MLS) routing." },
      { id: "PM-145", title: "Twilio webhooks: inbound SMS + delivery status callbacks", status: "done", date: "2026-03-13", notes: "Signature validation, STOP/START opt-out, dedup, phone mapping lookup, external agent sender_id=NULL, conversation-type-aware unread increment." },
      { id: "PM-146", title: "Resend inbound email webhook", status: "done", date: "2026-03-13", notes: "Svix signature verification, reply-to address parsing (conv-{uuid}@), reply chain stripping, sender authorization (participant or external agent), channel='email'." },
      { id: "PM-147", title: "Push token + SMS consent + delivery retry endpoints", status: "done", date: "2026-03-13", notes: "POST /api/profiles/push-token, POST /api/profiles/sms-consent (TCPA compliant with IP logging), GET /api/cron/delivery-retry (5-min cron, exponential backoff)." },
      { id: "PM-148", title: "Enhanced messages + conversations routes with notification routing", status: "done", date: "2026-03-13", notes: "External agent detection (source=mls), atomic increment_unread RPC, notifyRecipient/notifyExternalAgent on send, phone mapping upsert for SMS reply routing." },
      { id: "PM-149", title: "Mobile: push notifications, unread badges, notifications settings screen", status: "done", date: "2026-03-13", notes: "expo-notifications + expo-device. usePushNotifications hook registers token on login. useUnreadCount hook with Realtime subscription. Tab badge on Messages. Full notifications screen with push toggle, channel preference, SMS consent." },
      { id: "PM-150", title: "Admin: Messaging panel, Webhook Log panel, Template Editor panel", status: "done", date: "2026-03-13", notes: "3 new admin panels + 3 API routes. Messaging stats + recent convos. Filterable webhook log with expandable payloads. Template editor grouped by channel with inline editing." },
      { id: "PM-151", title: "Products panel: suppress/unsuppress, footnote, badge, split tables", status: "done", date: "2026-03-14", notes: "Suppress toggles is_active (hides from app, blocks Stripe). metadata.footnote + metadata.badge on ProductCard. Owner/Tenant workflow tables." },
      { id: "PM-152", title: "Renew page: dynamic pricing + service unavailable state", status: "done", date: "2026-03-14", notes: "Fetches price from products table instead of hardcoded $29.99. Shows unavailable message when listing product is suppressed." },
      { id: "PM-153", title: "Owner listing card: stacked status/expiry, stats column, view labels", status: "done", date: "2026-03-14", notes: "Status badge + expiry pill stacked vertically. Stats column: X Unique Views, X Contacts. Font matched to Outfit." },
      { id: "PM-154", title: "Tab bar font: switch to Outfit (match page titles)", status: "done", date: "2026-03-14" },
      { id: "PM-155", title: "Messages: remove Delete action, archive only", status: "done", date: "2026-03-14", notes: "Delete and Archive were identical (both archived). Removed Delete button, swipe hint, and API delete action." },
      { id: "PM-156", title: "Listed By section: stacked layout for long names/emails", status: "done", date: "2026-03-14", notes: "Label on top, value below right-justified. Full width for long agent names and emails." },
      { id: "PM-157", title: "Listing disclaimers: branch by source (MLS vs owner)", status: "done", date: "2026-03-14", notes: "MLS listings get IDX-required SEFMLS footer (locked). Owner listings get PadMagnet LLC disclaimer (admin-editable via site_config). Admin Disclaimers panel added to dashboard." },
      { id: "PM-158", title: "Share button redesign: orange pill with navy text", status: "done", date: "2026-03-14", notes: "brandOrange bg, dark navy text/icon. Header right slot changed from fixed width to minWidth for flexible content." },
      { id: "PM-159", title: "Hide PadScore from owner browse detail view", status: "done", date: "2026-03-14", notes: "PadScoreBreakdown hidden when context=owner_browse. Owners don't need tenant matching scores." },
      { id: "PM-160", title: "Nearby Rentals default radius: 3mi → 5mi for owners", status: "done", date: "2026-03-14" },
      { id: "PM-161", title: "Share templates: edit-mode gating + active/inactive toggle", status: "done", date: "2026-03-14", notes: "Share Templates section on dashboard now matches other template editors: Edit/Cancel/Save flow, Active/Inactive badge, Enable/Disable toggle. Mobile respects active flag." },
      { id: "PM-162", title: "EAS preview build: standalone APK for S24 Ultra", status: "done", date: "2026-03-14", notes: "Preview extends production profile. EXPO_PUBLIC_* env vars set on EAS (plaintext). Must uninstall old APK before installing new build." },
      { id: "PM-163", title: "Phase 0.5: Security hardening (12 items)", status: "done", date: "2026-03-16", notes: "admin-auth.js (cookie+bearer), input sanitization, config key whitelist, security headers (CSP/HSTS/X-Frame), timing-safe cron auth, owner role verification, SecureStore migration, phone prefill zero-rekey" },
      { id: "PM-164", title: "Design system unification: ~60 hardcoded values fixed", status: "done", date: "2026-03-16", notes: "Expanded colors.js (50+ tokens), fonts.js (10 sizes), layout.js (radius/padding/dimensions). DESIGN_TOKENS.md reference doc. Zero hardcoded styles remaining." },
      { id: "PM-165", title: "Phase 1: Freemium foundation", status: "done", date: "2026-03-16", notes: "Dead file archive, badges.js + tiers.js constants, admin brand color fix, NotificationPreferences shared component, useSubscription hook, TierBadge/UpgradeCTA/MarketStats components, migration 039 (tier columns + listing limit trigger + testimonials + analytics view)" },
      { id: "PM-166", title: "Phase 2: Owner flow redesign", status: "done", date: "2026-03-16", notes: "Services→Explore tab, listings empty state sales page, upgrade screen (3-tier), post-activation celebration, NearbyRentalsGate paywall removed (free for all), consent touchpoints (About You + Wizard Step 7), welcome social proof + founder quote, wizard micro-copy subtitles" },
      { id: "PM-167", title: "Nearby Rentals: GPS + address entry modes", status: "done", date: "2026-03-16", notes: "Location permission flow (check existing, branded pre-permission, OS dialog). GPS mode with 'search your property' option. Address entry via Google Places. Address cached in AsyncStorage for Create Listing prefill. Radius chips: 3/5/10mi." },
      { id: "PM-168", title: "Email confirmation: branded page + hash interceptor", status: "done", date: "2026-03-16", notes: "Self-contained /email-confirmed page (signup + email change). signUp() emailRedirectTo. Landing page hash fragment interceptor. auth/callback routes signup/email_change types." },
      { id: "PM-169", title: "Logo audit: primary icon on all dark surfaces", status: "done", date: "2026-03-16", notes: "5 web pages + mobile welcome screen switched to white-on-orange (2-4) variant. Secondary (cream bg) retained for light surfaces only." },
      { id: "PM-170", title: "Admin auth: cookie + bearer dual auth in requireAdmin", status: "done", date: "2026-03-16", notes: "Fixed admin dashboard API calls failing after requireAdmin was added. Dashboard uses cookies, mobile uses Bearer — both now work." },
      { id: "PM-171", title: "Keyboard buffer: all input screens get KAV + ScrollView + 360px padding", status: "done", date: "2026-03-16", notes: "9 screens fixed: auth (email, password, register, forgot-password), about-you, owner/create, owner/edit, settings/notifications, settings/preferences." },
      { id: "PM-172", title: "Places API: use dedicated GOOGLE_GEOCODING_KEY", status: "done", date: "2026-03-16", notes: "autocomplete + details routes switched from GOOGLE_SERVER_GEOCODING_KEY to GOOGLE_GEOCODING_KEY (Places-enabled key after rotation). Fallback for local dev." },
      { id: "PM-173", title: "Memory system cleanup: delete 7 obsolete files, trim 3, rewrite index", status: "done", date: "2026-03-22", notes: "MEMORY.md reduced from 214→76 lines. Deleted: swipe-system, nearby-rentals, landlord-data-pipeline, field-mapping-plan, role-architecture-fix, communications-plan, listing-lifecycle (duplicate)." },
      { id: "PM-174", title: "Stripe env vars on Vercel + live checkout working", status: "done", date: "2026-03-22", notes: "STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY added to Vercel production. Re-set via CLI to fix copy-paste issue." },
      { id: "PM-175", title: "Payment confirmation page (/payment-confirmed)", status: "done", date: "2026-03-22", notes: "Branded page for all Stripe outcomes: tier pass success (Pro/Premium features list), listing activation, cancelled, error. Replaced misused /email-confirmed redirect." },
      { id: "PM-176", title: "Subscription screen redesign", status: "done", date: "2026-03-22", notes: "Badge icon, days remaining countdown, included features list, Premium upsell for Pro users, expired/renew state, 'YOUR ACTIVE PLAN' green banner." },
      { id: "PM-177", title: "Proration credit for tier upgrades (Pro→Premium)", status: "done", date: "2026-03-22", notes: "Server-side: unused Pro days credited against Premium price. Client-side: credit banner + 'You pay today' display. Uses price_data for adjusted Stripe checkout amount." },
      { id: "PM-178", title: "Explore tab: plan status card + tier refresh on focus", status: "done", date: "2026-03-22", notes: "Plan card with badge icon, days remaining, tap→subscription. Premium upsell for Pro users. useFocusEffect refreshes tier." },
      { id: "PM-179", title: "useSubscription: fetch tier_expires_at + refresh()", status: "done", date: "2026-03-22", notes: "Hook now returns daysRemaining, isExpired, tierStartedAt, tierExpiresAt, refresh(). Used by subscription, explore, upgrade screens." },
      { id: "PM-180", title: "Post-purchase flow: refresh tier + navigate to subscription", status: "done", date: "2026-03-22", notes: "After WebBrowser closes: refreshTier() + router.replace('/settings/subscription'). Return to App button on payment-confirmed page using padmagnet:// deep link." },
      { id: "PM-181", title: "Owner tier badges on all listing surfaces", status: "done", date: "2026-03-22", notes: "TierBadge added to: My Listings thumbnail, Nearby Rentals subject card, PhotoGallery (detail + preview), single listing API enriched with owner_tier." },
      { id: "PM-182", title: "Unified Premium badge: golden diamond on blue", status: "done", date: "2026-03-22", notes: "Premium: diamond icon (gold) on accent blue 66% opacity. Pro: shield-checkmark (white) on solid accent blue. Consistent across all surfaces." },
      { id: "PM-183", title: "Email DNS: MX + SPF + DMARC records for padmagnet.com", status: "done", date: "2026-03-22", notes: "5 Google MX records, SPF (Google + Amazon SES), DMARC with reporting. All 8 email addresses verified working. Fixed duplicate DMARC record." },
      { id: "PM-184", title: "Landing page: fix hero overlap, update copy, remove nav CTA", status: "done", date: "2026-03-22", notes: "Hero padding 100→140px. Copy: 'Browse amazing rental homes.' Removed floating Join Waitlist button (off-screen on mobile)." },
      { id: "PM-185", title: "Landing page: footer links + privacy policy + terms of service", status: "done", date: "2026-03-22", notes: "Obfuscated mailto contact link, /privacy (10 sections), /terms (16 sections incl SMS Section 7 for Twilio compliance)." },
      { id: "PM-186", title: "Landing page: interactive coverage map with county polygons", status: "done", date: "2026-03-22", notes: "Leaflet map with 5 county boundary polygons (orange fill), hover tooltips, draggable/zoomable. CSP updated for unpkg.com." },
      { id: "PM-187", title: "Twilio A2P 10DLC registration submitted", status: "done", date: "2026-03-23", notes: "Brand BNcaa4e3576fb3eb2b670845f4950da260, Campaign CM0b1b1f1ba62a8e21f6036f8ea77d00ad. Pending vetting. All answers saved in memory." },
      { id: "PM-188", title: "Terms of Service: SMS Section 7 for CTIA/Twilio compliance", status: "done", date: "2026-03-23", notes: "Opt-in/out, HELP keyword, frequency, rates disclaimer, phone linking, privacy link. All CTIA required elements." },
      { id: "PM-189", title: "Upstash Redis rate limiting on 6 abuse-prone endpoints", status: "done", date: "2026-03-23", notes: "messages 20/min, swipes 60/min, conversations 5/min, photos 30/hr, listings 10/hr, webhooks 100/min by IP. Fails open." },
      { id: "PM-190", title: "Delete account flow (App Store requirement)", status: "done", date: "2026-03-23", notes: "API: Stripe cancel, archive listings, anonymize conversations/messages, clean storage, delete auth user. Mobile: type DELETE confirmation. Migration 041." },
      { id: "PM-191", title: "Global tier badges: owner_tier enrichment on nearby rentals API", status: "done", date: "2026-03-23", notes: "Nearby rentals API now enriches all owner listings with owner_tier. Badges show for ALL paid listings to ALL viewers on every surface." },
      { id: "PM-192", title: "Owner View Listing button on My Listings", status: "done", date: "2026-03-23", notes: "Tap card → preview. 2x2 action grid: View Listing, Edit Listing, Adjust Price, Archive. Pill-shaped white border buttons." },
      { id: "PM-193", title: "Nearby Rentals: subject card + filter panel side-by-side header", status: "done", date: "2026-03-23", notes: "Your Property card (60%) + Search Radius panel (37%) with radar icon. 1/3/5/10mi chips. Header stays visible during filter changes. Smooth comp grid transitions." },
      { id: "PM-194", title: "Unified share template: all share buttons use admin template", status: "done", date: "2026-03-24", notes: "New /api/templates/share reads from site_config. Shared mobile/lib/share-listing.js utility with 5-min cache. All 3 share locations (detail, preview, analytics) unified. 🧲 emoji now appears." },
      { id: "PM-195", title: "Wire notification emails to admin templates", status: "done", date: "2026-03-24", notes: "sendNotificationEmail reads from message_templates.new_message_email. sendExternalAgentEmail reads from message_templates.external_agent_email. Hardcoded HTML kept as fallback only." },
      { id: "PM-196", title: "Admin Templates: Supabase Auth emails note", status: "done", date: "2026-03-24", notes: "Added note at bottom of Templates panel listing 4 Supabase Auth emails (signup, reset, email change, magic link) with link to Supabase Dashboard." },
      { id: "PM-197", title: "Email template rule saved to memory", status: "done", date: "2026-03-24", notes: "All emails must use admin-editable templates. Never hardcode email content. feedback_email_template_rule.md created." },
      { id: "PM-198", title: "Stripe webhook: log signature failures to webhook_logs", status: "done", date: "2026-03-24", notes: "Signature verification failures now write to webhook_logs for admin visibility. Previously only console.error." },
      { id: "PM-199", title: "De-List/Re-List owner listing lifecycle", status: "done", date: "2026-03-24", notes: "Replace Archive with De-List (status=leased). Days remaining banked. Re-List resumes free if days remain, else routes to purchase. Migration 042." },
      { id: "PM-200", title: "De-list confirmation email with performance metrics", status: "done", date: "2026-03-24", notes: "listing_delisted template: DOM, unique views, contacts, days saved. Migration 043. Sent on delist API call." },
      { id: "PM-201", title: "Listing Paused dashboard (replaces preview for de-listed)", status: "done", date: "2026-03-24", notes: "Hero with status overlay, performance dashboard (2x2 grid + insight row), Re-List CTA with rocket icon + green glow. Zero-scroll to CTA." },
      { id: "PM-202", title: "SVG animated bar chart icon for Nearby Active Rentals", status: "done", date: "2026-03-24", notes: "react-native-svg based. 5 green bars, staggered build-in with bounce easing, breathing loop, L-shaped axis with tick marks." },
      { id: "PM-203", title: "My Listings card: hero text shadows + Ionicons upgrade", status: "done", date: "2026-03-24", notes: "Stronger text shadows (0.8 opacity, 5-6 radius) on all hero overlay text. Ionicons for action buttons (expand, create, pricetag, pause-circle)." },
      { id: "PM-204", title: "Nearby Rentals: subject card photo-only + filter refinements", status: "done", date: "2026-03-24", notes: "Subject card shows photo only (no text info), fixed 230px height. 65/32 split. Radius options: 2/5/7mi. Hero overlay with price/address/stats on subject." },
      { id: "PM-205", title: "Owner View Listing + share button on preview", status: "done", date: "2026-03-24", notes: "Preview screen has share button using unified shareListing(). Fixed hooks order bug (useCallback before early returns)." },
    ],
  },
  {
    category: "Ready to Build — Admin Dashboard",
    items: [
      { id: "T02", title: "Extract AdminLayout shell from monolith", status: "done", date: "2026-03-04", notes: "dashboard.js → shell (277 lines) + shared.js + demo-data.js" },
      { id: "T03", title: "Extract panels into separate files under panels/", status: "done", date: "2026-03-04", notes: "11 panel files in app/admin/panels/, zero behavior changes" },
      { id: "T04", title: "Wire Overview panel to real Supabase data", status: "done", date: "2026-03-07", notes: "Live stats, sync logs, owner listing signup, site_config persistence" },
      { id: "T05", title: "Wire Feeds panel to real sync_logs data", status: "pending", notes: "sync_logs table exists, UI still hardcoded" },
      { id: "T06", title: "Wire Listings panel to real data", status: "pending", notes: "Admin listings API exists, panel needs rewiring" },
      { id: "T07", title: "Wire PadScore panel to Supabase", status: "pending", notes: "padscore_configs table exists, need API + wire save" },
      { id: "T08", title: "Wire Billing panel to real data", status: "pending", notes: "Billing tables exist, panel is stub" },
      { id: "T-WL", title: "Wire Waitlist panel to real data", status: "done", date: "2026-03-04", notes: "Live Supabase data. Landlord→owner text updated 2026-03-12." },
      { id: "T-SM", title: "Splash message system (site_config table + Overview card + mobile display)", status: "pending", notes: "Admin-editable message on owner/tenant empty states" },
      { id: "T-RL", title: "Enable RLS on profiles table", status: "done", date: "2026-03-12", notes: "Migration 033. Own-row read/update, admin full access. Part of role architecture fix." },
      { id: "T-UR", title: "Unify role source of truth (profiles.role for all users)", status: "pending", notes: "Mobile reads user_metadata.role in some places — needs full migration to profiles. display_name refs already migrated (2026-03-12)." },
    ],
  },
  {
    category: "Ready to Build — Mobile App",
    items: [
      { id: "T-SL", title: "Shareable listing links (share button + public web page + OG tags + store badges)", status: "done", date: "2026-03-07", notes: "Share API on mobile, public listing page at padmagnet.com/listing/[id], OG meta for link previews, app store badges" },
      { id: "T-ME", title: "Mobile listing edit screen", status: "pending", notes: "PUT API exists, no mobile UI yet" },
      { id: "T-OF", title: "Owner create form: add 5 new owner fields", status: "pending", notes: "owner_special_comments, owner_application_link, owner_pet_policy_details, owner_utilities_included, owner_showing_instructions — API accepts them, no mobile UI yet" },
      { id: "T21", title: "Boost indicator badge on swipe cards", status: "pending", notes: "Subtle \"Boosted\" badge on boosted listings" },
    ],
  },
  {
    category: "Phase 2 — Owner Web Dashboard (/dashboard)",
    items: [
      { id: "T09", title: "Owner dashboard shell at /dashboard", status: "pending", notes: "Layout, auth, routes" },
      { id: "T10", title: "Owner listings management page", status: "pending", notes: "Web equivalent of mobile listings" },
      { id: "T11", title: "Owner listing detail with tabbed interface", status: "pending", notes: "Details, Calendar, Documents, Analytics tabs" },
      { id: "T12", title: "Calendar/availability/tour scheduling", status: "pending", notes: "DB tables exist, need API + UI" },
      { id: "T13", title: "Documents upload and send", status: "pending", notes: "DB table + storage bucket exist" },
      { id: "T15", title: "Email template editor (TipTap)", status: "pending", notes: "DB table exists" },
      { id: "T16", title: "Boost purchase flow for owners", status: "pending", notes: "Owner-facing boost API" },
      { id: "T18", title: "Owner analytics page", status: "pending", notes: "view_count works, need standalone page" },
    ],
  },
  {
    category: "Phase 3 — Mobile Polish",
    items: [
      { id: "T19", title: "Tenant tour request UI", status: "pending", notes: "Request Tour button + time slot picker" },
      { id: "T20", title: "Document viewer", status: "pending", notes: "PDF viewing + viewed_at tracking" },
      { id: "T22", title: "Owner billing screen", status: "pending", notes: "Wire up to purchase history + Stripe portal" },
      { id: "T23", title: "Multichannel message indicators", status: "pending", notes: "SMS/email/in-app channel icons on MessageBubble. Backend channel field already populated." },
    ],
  },
  {
    category: "Blocked / Deferred",
    items: [
      { id: "T14", title: "Twilio SMS live testing", status: "blocked", notes: "A2P 10DLC registration pending. Code complete — awaiting carrier approval to send to real numbers." },
      { id: "T17", title: "Owner billing UI (Stripe)", status: "blocked", notes: "Corporate entity + banking required" },
      { id: "T-ST", title: "Stripe activation (all payment flows)", status: "blocked", notes: "Corporate entity + banking required" },
      { id: "T-BR", title: "Bridge IDX sync", status: "done", date: "2026-03-07", notes: "Miami IDX feed live — 5-county filter (St Lucie to Miami-Dade), ~11,400 active rental listings" },
      { id: "T-EA", title: "EAS production build", status: "pending", notes: "Dev + preview builds working. Production build needed for Play Store submission (AAB format). Will need SHA-1 fingerprint for Google Maps key restriction." },
      { id: "T-AS", title: "App Store / Play Store submission", status: "deferred", notes: "After EAS build" },
      { id: "T-AP", title: "Revisit tenant product app_path values", status: "deferred", notes: "After tenant pages defined" },
      { id: "T-GM", title: "Google Maps: fresh GCP project + new API key + fix blank tiles", status: "done", date: "2026-03-08", notes: "New GCP project 'padmagnet-maps' under floridapm.net. Key unrestricted for now — TODO: restrict to Maps SDK + Geocoding API, add $1/month budget alert, add Android app restriction after production EAS build." },
      { id: "T-AY", title: "Add AssociationYN to Bridge sync for definitive association detection", status: "deferred", notes: "Currently using hoa_fee > 0 as proxy — add RESO field when Bridge access is live" },
      { id: "T-IS", title: "Incremental sync via ModificationTimestamp (10K+ scaling)", status: "deferred", notes: "Bridge $skip limit is 10K. Switch to timestamp-based delta sync when dataset grows. Weekly full reconciliation for deactivations." },
    ],
  },
];
