-- De-list confirmation email template (already inserted via Management API)
-- Kept here for migration file completeness
INSERT INTO email_templates (slug, subject, body_html, is_active, variables)
VALUES (
  'listing_delisted',
  '🧲 Your PadMagnet Listing Has Been De-Listed',
  '<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;background:#f8f9fa"><div style="background:#0F2B46;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">PadMagnet</h1></div><div style="background:#fff;padding:32px;border-radius:0 0 12px 12px"><h2 style="color:#0F2B46;margin:0 0 16px">Listing De-Listed</h2><p style="color:#444;line-height:1.6">Hi {{owner_name}},</p><p style="color:#444;line-height:1.6">Your rental listing at <strong>{{listing_address}}</strong> has been de-listed and is no longer visible to tenants.</p><div style="background:#f0f7ff;border-radius:8px;padding:20px;margin:20px 0"><h3 style="color:#0F2B46;margin:0 0 12px;font-size:16px">Your Listing Performance</h3><table style="width:100%;border-collapse:collapse"><tr><td style="padding:6px 0;color:#666;width:160px">Days on Market</td><td style="padding:6px 0;color:#333;font-weight:600">{{days_on_market}} days</td></tr><tr><td style="padding:6px 0;color:#666">Unique Views</td><td style="padding:6px 0;color:#333;font-weight:600">{{unique_views}}</td></tr><tr><td style="padding:6px 0;color:#666">Tenant Contacts</td><td style="padding:6px 0;color:#333;font-weight:600">{{contacts}}</td></tr><tr><td style="padding:6px 0;color:#666">Advertising Days Saved</td><td style="padding:6px 0;color:#333;font-weight:600">{{days_remaining}} days</td></tr></table></div><p style="color:#444;line-height:1.6">Your listing data, photos, and conversations are preserved. When you are ready to find a new tenant, you can re-list with one tap.</p><hr style="border:none;border-top:1px solid #eee;margin:24px 0"><p style="color:#999;font-size:12px;text-align:center">PadMagnet.com — Your perfect rental match awaits!<br>&copy; PadMagnet LLC</p></div></div>',
  true,
  '["owner_name","listing_address","days_on_market","unique_views","contacts","days_remaining"]'
) ON CONFLICT (slug) DO NOTHING;
