-- 058: Fix ALL email templates — add 🧲 branding, fix spacing, consistent wrapper

-- Fix subjects — add 🧲 emoji to all
UPDATE email_templates SET subject = '🧲 Your Listing is Live on PadMagnet!' WHERE slug = 'payment_confirmation';
UPDATE email_templates SET subject = '🧲 Your Listing Expires in 7 Days' WHERE slug = 'expiry_7day';
UPDATE email_templates SET subject = '🧲 Your Listing Expires in 3 Days' WHERE slug = 'expiry_3day';
UPDATE email_templates SET subject = '🧲 Last Day! Your Listing Expires Tomorrow' WHERE slug = 'expiry_1day';
UPDATE email_templates SET subject = '🧲 Your Listing Has Expired' WHERE slug = 'listing_expired';
UPDATE email_templates SET subject = '🧲 New Inquiry on Your Listing' WHERE slug = 'inquiry_alert';
UPDATE email_templates SET subject = '🧲 PadMagnet Payment Receipt' WHERE slug = 'receipt';
UPDATE email_templates SET subject = '🧲 Listing Submitted for Review — {{confirmation_code}}' WHERE slug = 'listing_submitted';
UPDATE email_templates SET subject = '🧲 You''re Live! Your Listing is Active — {{confirmation_code}}' WHERE slug = 'listing_approved';
UPDATE email_templates SET subject = '🧲 Your Listing Needs Changes — {{listing_address}}' WHERE slug = 'listing_rejected';
UPDATE email_templates SET subject = '🧲 Your PadMagnet Refund Has Been Processed' WHERE slug = 'refund_confirmation';
UPDATE email_templates SET subject = '🧲 Tour Confirmed — {{listing_address}}' WHERE slug = 'showing_confirmed';
UPDATE email_templates SET subject = '🧲 New Document from Your Landlord' WHERE slug = 'document_sent';

-- Fix listing_delisted — spacing issue on "Advertising Days Saved" row
UPDATE email_templates SET body_html =
'<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;background:#f8f9fa"><div style="background:#0F2B46;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">🧲 PadMagnet</h1></div><div style="background:#fff;padding:32px;border-radius:0 0 12px 12px"><h2 style="color:#0F2B46;margin:0 0 16px">Listing De-Listed</h2><p style="color:#444;line-height:1.6">Hi {{owner_name}},</p><p style="color:#444;line-height:1.6">Your rental listing at <strong>{{listing_address}}</strong> has been de-listed and is no longer visible to renters.</p><div style="background:#f0f7ff;border-radius:8px;padding:20px;margin:20px 0"><h3 style="color:#0F2B46;margin:0 0 12px;font-size:16px">Your Listing Performance</h3><table style="width:100%;border-collapse:collapse"><tr><td style="padding:8px 0;color:#666;width:180px">Days on Market</td><td style="padding:8px 0;color:#333;font-weight:600">{{days_on_market}} days</td></tr><tr><td style="padding:8px 0;color:#666">Unique Views</td><td style="padding:8px 0;color:#333;font-weight:600">{{unique_views}}</td></tr><tr><td style="padding:8px 0;color:#666">Tenant Contacts</td><td style="padding:8px 0;color:#333;font-weight:600">{{contacts}}</td></tr><tr><td style="padding:8px 0;color:#666">Advertising Days Saved</td><td style="padding:8px 0;color:#333;font-weight:600">{{days_remaining}} days</td></tr></table></div><p style="color:#444;line-height:1.6">Your listing data, photos, and conversations are preserved. When you are ready to find a new renter, you can re-list with one tap.</p><hr style="border:none;border-top:1px solid #eee;margin:24px 0"><p style="color:#999;font-size:12px;text-align:center">🧲 PadMagnet.com — Your perfect rental match awaits!<br>&copy; PadMagnet LLC</p></div></div>'
WHERE slug = 'listing_delisted';

-- Fix listing_submitted — add branded wrapper
UPDATE email_templates SET body_html =
'<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;background:#f8f9fa"><div style="background:#0F2B46;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">🧲 PadMagnet</h1></div><div style="background:#fff;padding:32px;border-radius:0 0 12px 12px"><h2 style="color:#0F2B46;margin:0 0 16px">Listing Submitted for Review</h2><p style="color:#444;line-height:1.6">Hi {{owner_name}},</p><p style="color:#444;line-height:1.6">Your listing at <strong>{{listing_address}}</strong> has been submitted and will appear in PadMagnet''s LIVE feed after a brief compliance review — generally much less than 24 hours.</p><div style="background:#f0f7ff;border-radius:8px;padding:20px;margin:20px 0"><h3 style="color:#0F2B46;margin:0 0 12px;font-size:16px">Listing Details</h3><table style="width:100%;border-collapse:collapse"><tr><td style="padding:8px 0;color:#666;width:180px">Confirmation Code</td><td style="padding:8px 0;color:#333;font-weight:600">{{confirmation_code}}</td></tr><tr><td style="padding:8px 0;color:#666">Rent</td><td style="padding:8px 0;color:#333;font-weight:600">{{rent}}</td></tr><tr><td style="padding:8px 0;color:#666">Type</td><td style="padding:8px 0;color:#333;font-weight:600">{{property_type}}</td></tr><tr><td style="padding:8px 0;color:#666">Beds / Baths</td><td style="padding:8px 0;color:#333;font-weight:600">{{beds_baths}}</td></tr><tr><td style="padding:8px 0;color:#666">Photos</td><td style="padding:8px 0;color:#333;font-weight:600">{{photo_count}}</td></tr></table></div><p style="color:#444;line-height:1.6">We''ll email you as soon as your listing is approved and live.</p><hr style="border:none;border-top:1px solid #eee;margin:24px 0"><p style="color:#999;font-size:12px;text-align:center">🧲 PadMagnet.com — Your perfect rental match awaits!<br>&copy; PadMagnet LLC</p></div></div>'
WHERE slug = 'listing_submitted';

-- Fix listing_rejected — add branded wrapper
UPDATE email_templates SET body_html =
'<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;background:#f8f9fa"><div style="background:#0F2B46;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">🧲 PadMagnet</h1></div><div style="background:#fff;padding:32px;border-radius:0 0 12px 12px"><h2 style="color:#0F2B46;margin:0 0 16px">Your Listing Needs Changes</h2><p style="color:#444;line-height:1.6">Hi {{owner_name}},</p><p style="color:#444;line-height:1.6">We reviewed your listing at <strong>{{listing_address}}</strong> and it needs some changes before we can make it live.</p><div style="background:#fff5f5;border-left:4px solid #e74c3c;border-radius:0 8px 8px 0;padding:16px 20px;margin:20px 0"><p style="color:#333;margin:0;line-height:1.6"><strong>Reason:</strong> {{rejection_reason}}</p></div><p style="color:#444;line-height:1.6">Please update your listing in the PadMagnet app and resubmit. If you have questions, contact us at <a href="mailto:support@padmagnet.com" style="color:#4A90D9">support@padmagnet.com</a>.</p><hr style="border:none;border-top:1px solid #eee;margin:24px 0"><p style="color:#999;font-size:12px;text-align:center">🧲 PadMagnet.com — Your perfect rental match awaits!<br>&copy; PadMagnet LLC</p></div></div>'
WHERE slug = 'listing_rejected';

-- Fix refund_confirmation — add branded wrapper
UPDATE email_templates SET body_html =
'<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;background:#f8f9fa"><div style="background:#0F2B46;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px">🧲 PadMagnet</h1></div><div style="background:#fff;padding:32px;border-radius:0 0 12px 12px"><h2 style="color:#0F2B46;margin:0 0 16px">Refund Confirmation</h2><p style="color:#444;line-height:1.6">Hi {{owner_name}},</p><p style="color:#444;line-height:1.6">We''ve processed a refund of <strong>{{amount}}</strong> for your listing at <strong>{{listing_address}}</strong>.</p><div style="background:#f0f7ff;border-radius:8px;padding:20px;margin:20px 0"><table style="width:100%;border-collapse:collapse"><tr><td style="padding:8px 0;color:#666;width:180px">Reason</td><td style="padding:8px 0;color:#333;font-weight:600">{{reason}}</td></tr><tr><td style="padding:8px 0;color:#666">Date</td><td style="padding:8px 0;color:#333;font-weight:600">{{refund_date}}</td></tr></table></div><p style="color:#444;line-height:1.6">The refund should appear on your statement within 5–10 business days depending on your bank.</p><p style="color:#444;line-height:1.6">If you have questions, contact us at <a href="mailto:support@padmagnet.com" style="color:#4A90D9">support@padmagnet.com</a>.</p><hr style="border:none;border-top:1px solid #eee;margin:24px 0"><p style="color:#999;font-size:12px;text-align:center">🧲 PadMagnet.com — Your perfect rental match awaits!<br>&copy; PadMagnet LLC</p></div></div>'
WHERE slug = 'refund_confirmation';

-- Add 🧲 to footer of existing templates that already have branded wrappers
UPDATE email_templates SET body_html = REPLACE(body_html, 'PadMagnet.com — Your perfect rental match awaits!', '🧲 PadMagnet.com — Your perfect rental match awaits!')
WHERE body_html LIKE '%PadMagnet.com — Your perfect rental match awaits!%'
  AND body_html NOT LIKE '%🧲 PadMagnet.com — Your perfect rental match awaits!%';
